name: tennis_env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - aniso8601=8.0.0
  - asn1crypto=1.3.0
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.1
  - cryptography=2.8
  - flask=1.1.1
  - flask-restful=0.3.7
  - flask-sqlalchemy=2.4.0
  - idna=2.9
  - itsdangerous=1.1.0
  - jinja2=2.11.1
  - joblib=0.14.1
  - krb5=1.16.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=9.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=4.0.0
  - liblapack=3.8.0
  - libopenblas=0.3.9
  - libpq=11.2
  - libxgboost=1.0.2
  - llvm-openmp=9.0.1
  - markupsafe=1.1.1
  - ncurses=6.1
  - numpy=1.18.1
  - openssl=1.1.1
  - pandas=1.0.2
  - pip=20.0.2
  - psycopg2=2.8.4
  - py-xgboost=1.0.2
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.8.1
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2019.3
  - readline=7.0
  - requests=2.23.0
  - scikit-learn=0.22.2.post1
  - scipy=1.4.1
  - setuptools=46.0.0
  - six=1.14.0
  - sqlalchemy=1.3.15
  - sqlite=3.31.1
  - tk=8.6.10
  - urllib3=1.25.8
  - werkzeug=1.0.0
  - wheel=0.34.2
  - xgboost=1.0.2
  - xz=5.2.4
  - zlib=1.2.11
